In [1]:
import numpy as np
import pandas as pd

In [2]:
# File 1: Shipments Data
shipments_data = {
    'Shipment_ID': [f'SHP_{100+i}' for i in range(50)],
    'Vehicle_ID': [f'VEH_{(i%10)+1}' for i in range(50)],
    'Region_ID': [f'REG_{(i%5)+1}' for i in range(50)],
    'Distance_KM': [120, 450, 80, 600, 310, 150, 520, 210, 750, 90, 340, 180, 620, 290, 410, 110, 800, 230, 500, 140, 380, 260, 710, 190, 440, 160, 680, 220, 530, 130, 360, 270, 740, 170, 490, 150, 650, 240, 580, 200, 420, 280, 790, 180, 460, 210, 630, 250, 510, 300],
    'Cargo_Weight_Tons': [5.2, 18.0, 2.1, 22.5, 12.0, 4.5, 19.8, 8.1, 24.0, 3.0, 14.2, 6.0, 21.0, 10.5, 16.0, 4.0, 25.0, 7.5, 18.5, 5.0, 13.5, 9.0, 23.0, 6.5, 17.0, 5.5, 22.0, 8.0, 19.0, 4.8, 13.0, 9.5, 24.5, 6.2, 17.5, 5.8, 21.5, 8.5, 20.0, 7.0, 15.5, 10.0, 24.8, 6.8, 16.5, 7.8, 21.2, 8.8, 18.8, 11.0],
    'Actual_Delay_Hours': [0.5, 4.2, 0.0, 6.5, 1.2, 0.0, 5.1, 0.8, 8.0, 0.0, 2.5, 0.2, 7.1, 1.0, 3.8, 0.0, 9.2, 0.5, 4.8, 0.1, 2.8, 0.9, 7.8, 0.3, 3.5, 0.1, 6.9, 0.6, 5.2, 0.0, 2.1, 0.7, 8.5, 0.2, 4.1, 0.0, 6.2, 0.8, 5.5, 0.4, 3.0, 1.1, 8.9, 0.3, 3.9, 0.7, 6.0, 1.0, 4.9, 1.5],
    'Is_Delayed': ['No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No']
}

# File 2: Fleet Metadata
fleet_data = {
    'Vehicle_ID': [f'VEH_{i}' for i in range(1, 11)],
    'Vehicle_Age_Years': [2, 8, 1, 12, 5, 3, 9, 4, 11, 2],
    'Maintenance_Score': [95, 62, 98, 45, 78, 88, 55, 82, 48, 91],
    'Driver_Experience_Yrs': [8, 3, 12, 2, 6, 9, 4, 7, 1, 10]
}

# File 3: Regional Weather Logs
weather_data = {
    'Region_ID': [f'REG_{i}' for i in range(1, 6)],
    'Weather_Condition': ['Clear', 'Heavy Rain', 'Fog', 'Clear', 'Storm'],
    'Traffic_Congestion_Index': [2.1, 8.5, 6.2, 3.0, 9.1]
}

df_shipments = pd.DataFrame(shipments_data)
df_fleet = pd.DataFrame(fleet_data)
df_weather = pd.DataFrame(weather_data)

In [3]:
df_integrated=df_shipments.merge(df_fleet,on='Vehicle_ID',how='left')

In [4]:
df_integrated=df_integrated.merge(df_weather,on='Region_ID',how='left')

In [5]:
df_integrated.head()

,Shipment_ID,Vehicle_ID,Region_ID,Distance_KM,Cargo_Weight_Tons,Actual_Delay_Hours,Is_Delayed,Vehicle_Age_Years,Maintenance_Score,Driver_Experience_Yrs,Weather_Condition,Traffic_Congestion_Index
0,SHP_100,VEH_1,REG_1,120,5.2,0.5,No,2,95,8,Clear,2.1
1,SHP_101,VEH_2,REG_2,450,18.0,4.2,Yes,8,62,3,Heavy Rain,8.5
2,SHP_102,VEH_3,REG_3,80,2.1,0.0,No,1,98,12,Fog,6.2
3,SHP_103,VEH_4,REG_4,600,22.5,6.5,Yes,12,45,2,Clear,3.0
4,SHP_104,VEH_5,REG_5,310,12.0,1.2,No,5,78,6,Storm,9.1

In [6]:
print("Dataset profile")
print("Row count",df_integrated.shape[0])
print("Total Columns:", df_integrated.shape[1])
memory_mb=df_integrated.memory_usage(deep=True).sum()/(1024**2)
print(f"Memory Usage: {memory_mb:.4f} MB")
print("data types")
print(df_integrated.dtypes)

Dataset profile
Row count 50
Total Columns: 12
Memory Usage: 0.0157 MB
data types
Shipment_ID                  object
Vehicle_ID                   object
Region_ID                    object
Distance_KM                   int64
Cargo_Weight_Tons           float64
Actual_Delay_Hours          float64
Is_Delayed                   object
Vehicle_Age_Years             int64
Maintenance_Score             int64
Driver_Experience_Yrs         int64
Weather_Condition            object
Traffic_Congestion_Index    float64
dtype: object

In [7]:
df_integrated.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Shipment_ID               50 non-null     object
 1   Vehicle_ID                50 non-null     object
 2   Region_ID                 50 non-null     object
 3   Distance_KM               50 non-null     int64
 4   Cargo_Weight_Tons         50 non-null     float64
 5   Actual_Delay_Hours        50 non-null     float64
 6   Is_Delayed                50 non-null     object
 7   Vehicle_Age_Years         50 non-null     int64
 8   Maintenance_Score         50 non-null     int64
 9   Driver_Experience_Yrs     50 non-null     int64
 10  Weather_Condition         50 non-null     object
 11  Traffic_Congestion_Index  50 non-null     float64
dtypes: float64(3), int64(4), object(5)
memory usage: 4.8+ KB

In [8]:
target = 'Is_Delayed'

drop_columns = [
    'Shipment_ID',
    'Vehicle_ID',
    'Region_ID',
    'Is_Delayed'
]

X=df_integrated.drop(columns=drop_columns)
y=df_integrated[target]

In [9]:
numerical_features=X.select_dtypes(
    include=np.number
).columns.tolist()

categorical_features=X.select_dtypes(
    exclude=np.number
).columns.tolist()

print("Numerical features")
print(numerical_features)

print("Categorical features")
print(categorical_features)

Numerical features
['Distance_KM', 'Cargo_Weight_Tons', 'Actual_Delay_Hours', 'Vehicle_Age_Years', 'Maintenance_Score', 'Driver_Experience_Yrs', 'Traffic_Congestion_Index']
Categorical features
['Weather_Condition']

In [10]:
target_counts=y.value_counts()
print(target_counts)

target_percentages=y.value_counts(normalize=True)*100
print(target_percentages)

Is_Delayed
No     26
Yes    24
Name: count, dtype: int64
Is_Delayed
No     52.0
Yes    48.0
Name: proportion, dtype: float64

In [11]:
group_metrics=df_integrated.groupby('Is_Delayed')[['Distance_KM','Maintenance_Score']].mean()
print(group_metrics.round(2))

            Distance_KM  Maintenance_Score
Is_Delayed
No               196.92              77.08
Yes              556.67              71.08

In [12]:
condition1=(
    (df_integrated['Distance_KM']>400) & (df_integrated['Maintenance_Score']<60)
)

In [13]:
condition2=(
    df_integrated['Weather_Condition'].isin( ['Storm', 'Heavy Rain'])
)

In [14]:
rule=condition1 | condition2

In [15]:
df_integrated['Rule_Prediction']=np.where(
    rule,
    'Yes',
    'No'
)

In [16]:
df_integrated[
    [
        'Shipment_ID',
        'Distance_KM',
        'Maintenance_Score',
        'Weather_Condition',
        'Rule_Prediction'
    ]
].head(10)

,Shipment_ID,Distance_KM,Maintenance_Score,Weather_Condition,Rule_Prediction
0,SHP_100,120,95,Clear,No
1,SHP_101,450,62,Heavy Rain,Yes
2,SHP_102,80,98,Fog,No
3,SHP_103,600,45,Clear,Yes
4,SHP_104,310,78,Storm,Yes
5,SHP_105,150,88,Clear,No
6,SHP_106,520,55,Heavy Rain,Yes
7,SHP_107,210,82,Fog,No
8,SHP_108,750,48,Clear,Yes
9,SHP_109,90,91,Storm,Yes

In [17]:
correct_predictions = (
    df_integrated['Rule_Prediction'] ==
    df_integrated['Is_Delayed']
).sum()

print("Correct Predictions:", correct_predictions)

Correct Predictions: 32

In [18]:
accuracy=(df_integrated['Rule_Prediction']==df_integrated['Is_Delayed']).mean()*100
print(f"Accuracy :{accuracy:.2f}%")

Accuracy :64.00%

In [19]:
false_positive_cases=df_integrated[(df_integrated['Is_Delayed']=='No') & (df_integrated['Rule_Prediction']=='Yes')]
false_positive_cases[
    [
        'Shipment_ID',
        'Distance_KM',
        'Maintenance_Score',
        'Weather_Condition',
        'Traffic_Congestion_Index',
        'Is_Delayed',
        'Rule_Prediction'
    ]
]

,Shipment_ID,Distance_KM,Maintenance_Score,Weather_Condition,Traffic_Congestion_Index,Is_Delayed,Rule_Prediction
4,SHP_104,310,78,Storm,9.1,No,Yes
9,SHP_109,90,91,Storm,9.1,No,Yes
11,SHP_111,180,62,Heavy Rain,8.5,No,Yes
19,SHP_119,140,91,Storm,9.1,No,Yes
21,SHP_121,260,62,Heavy Rain,8.5,No,Yes
29,SHP_129,130,91,Storm,9.1,No,Yes
31,SHP_131,270,62,Heavy Rain,8.5,No,Yes
39,SHP_139,200,91,Storm,9.1,No,Yes
41,SHP_141,280,62,Heavy Rain,8.5,No,Yes
49,SHP_149,300,91,Storm,9.1,No,Yes

In [20]:
print("=" * 60)
print("      ENTERPRISE LOGISTICS DELAY ANALYTICS")
print("=" * 60)

# Dataset information
print(f"\nIntegrated Dataset Records : {len(df_integrated)}")
print(f"Total Combined Columns    : {df_integrated.shape[1]}")
print(f"Predictor Features        : {X.shape[1]}")

# Target distribution
no_count = (df_integrated['Is_Delayed'] == 'No').sum()
yes_count = (df_integrated['Is_Delayed'] == 'Yes').sum()

no_pct = no_count / len(df_integrated) * 100
yes_pct = yes_count / len(df_integrated) * 100

print(
    f"Target Class Distribution : "
    f"No = {no_count} ({no_pct:.1f}%), "
    f"Yes = {yes_count} ({yes_pct:.1f}%)"
)

# Group metrics
metrics = df_integrated.groupby('Is_Delayed')[
    ['Distance_KM', 'Maintenance_Score']
].mean()

print("\nGroup Metrics (Delayed vs On-Time):")

print(
    f"- Mean Distance            : "
    f"Delayed = {metrics.loc['Yes', 'Distance_KM']:.2f} KM | "
    f"On-Time = {metrics.loc['No', 'Distance_KM']:.2f} KM"
)

print(
    f"- Mean Vehicle Maintenance : "
    f"Delayed = {metrics.loc['Yes', 'Maintenance_Score']:.2f} Score | "
    f"On-Time = {metrics.loc['No', 'Maintenance_Score']:.2f} Score"
)

# Rule evaluation
correct = (
    df_integrated['Rule_Prediction'] ==
    df_integrated['Is_Delayed']
).sum()

accuracy = correct / len(df_integrated) * 100

fp = (
    (df_integrated['Is_Delayed'] == 'No') &
    (df_integrated['Rule_Prediction'] == 'Yes')
).sum()

fn = (
    (df_integrated['Is_Delayed'] == 'Yes') &
    (df_integrated['Rule_Prediction'] == 'No')
).sum()

print("\nRule Engine Evaluation:")
print(f"- Rule Accuracy           : {accuracy:.2f}%")
print(f"- Correct Predictions     : {correct}")
print(f"- False Positives         : {fp}")
print(f"- False Negatives         : {fn}")

print("\nConclusion:")
print(
    "Multi-source integration combines shipment, fleet, and weather "
    "information into a single analytical dataset. The supplied rule "
    "achieves 64% accuracy, with 10 false positives and 8 false negatives. "
    "The failures demonstrate that fixed thresholds cannot fully capture "
    "the interactions among distance, vehicle condition, congestion, "
    "weather, cargo, and driver-related factors. These integrated features "
    "can therefore serve as the foundation for a future machine-learning "
    "classification model."
)

============================================================
      ENTERPRISE LOGISTICS DELAY ANALYTICS
============================================================

Integrated Dataset Records : 50
Total Combined Columns    : 13
Predictor Features        : 8
Target Class Distribution : No = 26 (52.0%), Yes = 24 (48.0%)

Group Metrics (Delayed vs On-Time):
- Mean Distance            : Delayed = 556.67 KM | On-Time = 196.92 KM
- Mean Vehicle Maintenance : Delayed = 71.08 Score | On-Time = 77.08 Score

Rule Engine Evaluation:
- Rule Accuracy           : 64.00%
- Correct Predictions     : 32
- False Positives         : 10
- False Negatives         : 8

Conclusion:
Multi-source integration combines shipment, fleet, and weather information into a single analytical dataset. The supplied rule achieves 64% accuracy, with 10 false positives and 8 false negatives. The failures demonstrate that fixed thresholds cannot fully capture the interactions among distance, vehicle condition, congestion, weather, cargo, and driver-related factors. These integrated features can therefore serve as the foundation for a future machine-learning classification model.